In [8]:
import cv2 as cv
import numpy as np
img = cv.imread('Sudoko.png')
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
edges = cv.Canny(gray,50,150,apertureSize = 3)
lines = cv.HoughLines(edges,1,np.pi/180,200)
print(lines)
for line in lines:
    rho,theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))
    cv.line(img,(x1,y1),(x2,y2),(0,0,255),2)
cv.imwrite('houghlines3.jpg',img)

[[[ 1.3500000e+02  1.5707964e+00]]

 [[-4.0500000e+02  3.0717795e+00]]

 [[ 2.4300000e+02  0.0000000e+00]]

 [[ 4.5300000e+02  1.5707964e+00]]

 [[-3.5100000e+02  3.0892327e+00]]

 [[-3.5600000e+02  3.0892327e+00]]

 [[ 2.4700000e+02  0.0000000e+00]]

 [[ 1.0000000e+00  0.0000000e+00]]

 [[ 1.7500000e+02  1.5707964e+00]]

 [[-4.0300000e+02  3.0717795e+00]]

 [[-3.9500000e+02  3.0717795e+00]]

 [[-2.8300000e+02  3.1241393e+00]]

 [[-3.9200000e+02  3.0717795e+00]]

 [[-3.9800000e+02  3.0717795e+00]]

 [[-4.0000000e+02  3.0717795e+00]]

 [[-3.1900000e+02  3.1066861e+00]]

 [[-4.1200000e+02  3.0717795e+00]]

 [[ 2.5200000e+02  1.5707964e+00]]

 [[ 2.4800000e+02  1.5707964e+00]]

 [[-3.1400000e+02  3.1066861e+00]]

 [[ 3.2900000e+02  1.5707964e+00]]

 [[-4.1000000e+02  3.0717795e+00]]

 [[ 1.7000000e+02  1.5707964e+00]]

 [[ 1.7600000e+02  3.4906585e-02]]

 [[-4.0800000e+02  3.0717795e+00]]]


True